# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

variables:
  RELEASE_REGISTRY_IMAGE: index.docker.io/magentaaps/os2mint-omada
  IMAGE_SHA: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
  PRECOMMIT_USE_POETRY: "true"
  POETRY_VERSION: "1.3"
  PYTEST_COV_MODULE: os2mint_omada
  PYTEST_COV_FAIL_UNDER: 0
  OS2MO_INIT_CONFIG: "/builds/$CI_PROJECT_PATH/init.config.yml"


stages:
  - lint
  - test
  - coverage
  - build
  - release
  - deploy


# Global Conditions
.if-default-branch-refs: &if-default-branch-refs
  if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

.if-tag: &if-tag
  if: '$CI_COMMIT_TAG'

.if-merge-request: &if-merge-request
  if: '$CI_MERGE_REQUEST_IID'


workflow:
  rules:
    - <<: *if-tag
      variables:
        # Override the IMAGE_SHA variable on tag pipelines to avoid both the default
        # branch pipeline and tag pipeline overriding each other's images arbitrarily when
        # they are both running at the same time on master.
        IMAGE_SHA: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
    - <<: *if-default-branch-refs
    - <<: *if-merge-request


include:
  - project: labs/salt-automation
    file:
      - gitlab-ci-templates/common/conventional-commits.v1.yml
      - gitlab-ci-templates/common/pre-commit.v1.yml
      - gitlab-ci-templates/python/pytest.v1.yml
      - gitlab-ci-templates/common/docker-build.v1.yml
      - gitlab-ci-templates/common/docker-release.v1.yml
      - gitlab-ci-templates/common/config-updater-meta.v1.yml
  - project: rammearkitektur/os2mo
    file:
      - gitlab-ci-templates/integration-test-meta.v1.yml


# Test
Test:
  variables:
    PYTEST_ADDOPTS: "-m 'not integration_test'"


Integration-test:
  extends:
    - .integration-test:mo
  variables:
    # OS2mo
    FASTRAMQPI__MO_URL: "http://mo:5000"
    FASTRAMQPI__CLIENT_ID: "dipex"
    FASTRAMQPI__CLIENT_SECRET: "603f1c82-d012-4d04-9382-dbe659c533fb"
    FASTRAMQPI__AUTH_SERVER: "http://keycloak:8080/auth"
    FASTRAMQPI__AUTH_REALM: "mo"
    FASTRAMQPI__AMQP__URL: "amqp://guest:guest@msg-broker:5672/"

    # Omada
    OMADA__AMQP__URL: "amqp://guest:guest@msg-broker:5672/"


# Release
Deploy to Flux Dev:
  extends: .release-to-dev
  needs:
    - Release version
  variables:
    ENDPOINT: os2mo/flux/omada/update-dev

Deploy to Flux Test:
  extends: .release-to-test
  needs: []
  variables:
    ENDPOINT: os2mo/flux/omada/update-test

Deploy to Flux Prod:
  extends: .release-to-prod
  needs: []
  variables:
    ENDPOINT: os2mo/flux/omada/update-prod

Deploy to Salt Dev:
  extends: .release-to-dev
  needs:
    - Release version
  variables:
    ENDPOINT: os2mo/salt/omada/update-dev

Deploy to Salt Test:
  extends: .release-to-test
  needs: []
  variables:
    ENDPOINT: os2mo/salt/omada/update-test

Deploy to Salt Prod:
  extends: .release-to-prod
  needs: []
  variables:
    ENDPOINT: os2mo/salt/omada/update-prod
