# SPDX-FileCopyrightText: Magenta ApS
# SPDX-License-Identifier: MPL-2.0
---
services:
  init:
    image: magentaaps/os2mo-init:1.0
    environment:
      # Keycloak
      AUTH_SERVER: "http://keycloak:8080/auth"
      # OS2mo
      MO_URL: "http://mo"
      CLIENT_ID: "dipex"
      CLIENT_SECRET: "603f1c82-d012-4d04-9382-dbe659c533fb"
      # LoRa
      LORA_URL: "http://mo/lora"
    volumes:
      - type: bind
        source: ./init.config.yml
        target: /config/config.yml
        read_only: true

  omada:
    build: .
    command: ["uvicorn", "os2mint_omada.main:app", "--host", "0.0.0.0", "--reload"]
    environment:
      LOG_LEVEL: DEBUG

      # OS2mo
      MO__URL: "http://mo"
      MO__AUTH__CLIENT_ID: "dipex"
      MO__AUTH__CLIENT_SECRET: "603f1c82-d012-4d04-9382-dbe659c533fb"
      MO__AUTH__REALM: "mo"
      MO__AUTH__SERVER: "http://keycloak:8080/auth"
      MO__AMQP__URL: "amqp://guest:guest@msg_broker:5672/"

      # Omada
      OMADA__URL: "http://omada-api/odata.json"
      OMADA__AMQP__URL: "amqp://guest:guest@msg_broker:5672/"
      OMADA__INTERVAL: 30
    ports:
      - "127.0.0.1:9000:8000"
    volumes:
      - ./os2mint_omada:/app/os2mint_omada:ro
    depends_on:
      init:
        condition: service_completed_successfully

  omada-api:
    image: nginx:latest
    volumes:
      - ./docs/odata.dataobjects.identity.view.json:/usr/share/nginx/html/odata.json:ro

networks:
  default:
    external: true
    name: os2mo_default
