[tool.poetry]
name = "os2mint_omada"
version = "4.3.0"
description = "OS2mo Omada integration"
authors = ["Magenta <info@magenta.dk>"]
license = "MPL-2.0"
readme = "README.md"
homepage = "https://magenta.dk/"
repository = "https://git.magenta.dk/rammearkitektur/os2mint/os2mint-omada"
keywords = ["os2mo", "os2mint", "omada"]

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^1.10.2"
structlog = "^22.3.0"
fastapi = "^0.88.0"
uvicorn = "^0.17.6"
httpx = "^0.23.0"
ramodels = "^15.5.1"
raclients = "3.0.3"
ramqp = "6.7.2"
prometheus-fastapi-instrumentator = "^5.8.2"
more-itertools = "^9.0.0"
ra-utils = "^1.2.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.2"
black = "^22.8.0"
flake8 = "^5.0.4"
mypy = "^0.991"
reorder-python-imports = "^3.1.0"
pre-commit = "^2.20.0"
pytest-cov = "^3.0.0"
pytest-env = "^0.6.2"
respx = "^0.20.1"
pytest-asyncio = "^0.18.3"
freezegun = "^1.2.1"
types-freezegun = "^1.1.10"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
asyncio_mode="auto"

[tool.autopub]
git-username = "MagentaBot"
git-email = "info@magenta.dk"

[tool.mypy]
plugins = ["pydantic.mypy"]

[[tool.mypy.overrides]]  # TODO
module = "tests.*"
ignore_errors = true
