[tool.poetry]
name = "os2mint_omada"
version = "0.0.1"
description = "OS2mo Omada integration"
authors = ["Magenta <info@magenta.dk>"]
license = "MPL-2.0"
readme = "README.md"
homepage = "https://magenta.dk/"
repository = "https://git.magenta.dk/rammearkitektur/os2mint/os2mint-omada"
keywords = ["os2mo", "os2mint", "omada"]

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^1.8.2"
fastapi = "^0.70.0"
uvicorn = "^0.15.0"
httpx = "^0.20.0"
hypothesis = "^6.24.5"
ramodels = "^3.8.0"
raclients = "^0.9.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
black = "^21.9b0"
flake8 = "^4.0.1"
mypy = "^0.910"
reorder-python-imports = "^2.6.0"
pre-commit = "^2.15.0"
pytest-cov = "^3.0.0"
respx = "^0.18.2"
pytest-asyncio = "^0.16.0"
freezegun = "^1.1.0"
types-freezegun = "^1.1.3"

[tool.autopub]
git-username = "MagentaBot"
git-email = "info@magenta.dk"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
