[tool.poetry]
name = "os2mint_omada"
version = "0.4.0"
description = "OS2mo Omada integration"
authors = ["Magenta <info@magenta.dk>"]
license = "MPL-2.0"
readme = "README.md"
homepage = "https://magenta.dk/"
repository = "https://git.magenta.dk/rammearkitektur/os2mint/os2mint-omada"
keywords = ["os2mo", "os2mint", "omada"]

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^1.9.0"
fastapi = "^0.72.0"
uvicorn = "^0.17.0"
httpx = "^0.21.3"
ramodels = "^5.0.0"
raclients = "^0.11.4"
# TODO: Fix when https://github.com/ulodciv/httpx-ntlm/pull/7 is merged upstream
httpx-ntlm = { git = "https://github.com/magenta-aps/httpx-ntlm.git", tag = "v1.0.0" }

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
black = "^21.11b1"
flake8 = "^4.0.1"
mypy = "^0.910"
reorder-python-imports = "^2.6.0"
pre-commit = "^2.15.0"
pytest-cov = "^3.0.0"
pytest-env = "^0.6.2"
respx = "^0.19.0"
pytest-asyncio = "^0.16.0"
hypothesis = "^6.29.0"
freezegun = "^1.1.0"
types-freezegun = "^1.1.3"

[tool.pytest.ini_options]
env = [
    "D:CLIENT_SECRET = 603f1c82-d012-4d04-9382-dbe659c533fb",
    "D:IT_SYSTEM_USER_KEY = omada_ad_guid",
    "D:ODATA_URL = http://omada.example.org/OData/DataObjects/Identity?viewid=12345",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.autopub]
git-username = "MagentaBot"
git-email = "info@magenta.dk"
