[tool.poetry]
name = "os2mint_omada"
version = "1.0.2"
description = "OS2mo Omada integration"
authors = ["Magenta <info@magenta.dk>"]
license = "MPL-2.0"
readme = "README.md"
homepage = "https://magenta.dk/"
repository = "https://git.magenta.dk/rammearkitektur/os2mint/os2mint-omada"
keywords = ["os2mo", "os2mint", "omada"]

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^1.9.1"
structlog = "^21.5.0"
fastapi = "^0.78.0"
uvicorn = "^0.17.6"
httpx = "^0.23.0"
ramodels = "~7.0.2"
raclients = "^1.2.5"
ramqp = "^6.1.0"
httpx-ntlm = "^1.0.0"
prometheus-fastapi-instrumentator = "^5.8.2"
more-itertools = "^8.13.0"
ra-utils = "^1.2.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
black = "^22.3.0"
flake8 = "^4.0.1"
mypy = "^0.961"
reorder-python-imports = "^3.1.0"
pre-commit = "^2.19.0"
pytest-cov = "^3.0.0"
pytest-env = "^0.6.2"
respx = "^0.19.2"
pytest-asyncio = "^0.18.3"
freezegun = "^1.2.1"
types-freezegun = "^1.1.10"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
asyncio_mode="auto"

[tool.autopub]
git-username = "MagentaBot"
git-email = "info@magenta.dk"
