# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from collections.abc import AsyncIterator
from collections.abc import Callable
from pathlib import Path
from typing import Awaitable

import pytest
from fastapi import FastAPI
from fastramqpi.ramqp.depends import rate_limit
from httpx import AsyncClient
from pydantic import AmqpDsn
from pydantic import AnyHttpUrl
from pydantic import parse_obj_as
from pytest import MonkeyPatch
from respx import ASGIHandler
from respx import MockRouter

from os2mint_omada.app import create_app
from os2mint_omada.autogenerated_graphql_client import GraphQLClient
from os2mint_omada.config import OmadaAMQPConnectionSettings
from os2mint_omada.config import OmadaSettings
from os2mint_omada.omada.api import OmadaAPI
from os2mint_omada.omada.api import create_client
from tests.fakes import fake_omada_api


@pytest.fixture
async def omada_mock(respx_mock: MockRouter) -> Callable[[list], None]:
    """Allow tests to fake the Omada API."""

    def _omada_mock(values: list) -> None:
        app = fake_omada_api.create_app(values=values)
        respx_mock.route(host="fake-omada-api").mock(side_effect=ASGIHandler(app))

    # Start mocking an empty Omada view immediately in case the integration makes calls
    # before the test configures its mock users through the callback.
    _omada_mock([])
    return _omada_mock


@pytest.fixture
async def app(monkeypatch: MonkeyPatch, tmp_path: Path) -> FastAPI:
    monkeypatch.setenv("OMADA__URL", "http://fake-omada-api/")
    monkeypatch.setenv("OMADA__INTERVAL", "1")
    monkeypatch.setenv("OMADA__PERSISTENCE_FILE", str(tmp_path / "omada.json"))

    app = create_app()

    # Decrease rate-limit to avoid tests (and developers) timing out
    app.dependency_overrides[rate_limit()] = rate_limit(1)

    return app


@pytest.fixture
async def graphql_client(mo_client: AsyncClient) -> AsyncIterator[GraphQLClient]:
    """Authenticated GraphQL codegen client for OS2mo."""
    graphql_client = GraphQLClient(
        url=f"{mo_client.base_url}/graphql/v22",
        http_client=mo_client,
    )
    async with graphql_client as client:
        yield client


@pytest.fixture
async def omada_api(tmp_path: Path) -> AsyncIterator[OmadaAPI]:
    """A real OmadaAPI whose HTTP calls are intercepted by the `omada_mock`."""
    settings = OmadaSettings(
        url=parse_obj_as(AnyHttpUrl, "http://fake-omada-api/"),
        amqp=OmadaAMQPConnectionSettings(
            url=parse_obj_as(AmqpDsn, "amqp://guest:guest@msg-broker:5672/"),
        ),
        persistence_file=tmp_path / "omada.json",
    )
    client = create_client(settings)
    async with client:
        yield OmadaAPI(url=settings.url, client=client)


@pytest.fixture
def get_num_queued_messages(
    rabbitmq_management_client: AsyncClient,
) -> Callable[[], Awaitable[int]]:
    """Get number of queued messages in RabbitMQ AMQP."""

    async def _get_num_queued_messages() -> int:
        queues = (await rabbitmq_management_client.get("queues")).json()
        return sum(
            queue.get("messages_ready", 0) + queue.get("messages_unacknowledged", 0)
            for queue in queues
        )

    return _get_num_queued_messages
